### ISSUE TITLE
Crashing (1.8) - NPE in item registry

### ISSUE THREAD

**Issue by FarLanderCraft** [ViaVersion/ViaFabric#107]
**Describe the bug, provide any errors**
I hate this template...

ViaFabric 1.8.9 causes Minecraft to crash whenever I connect to any server, except for 1.8 servers, which crash shortly thereafter.
Single player doesn't even attempt, it just instantly freezes.

**How can we reproduce it?**
1. Use ViaFabric 1.8.9
2. Join any server

**Expected behaviour**
A log similar to this:
https://del.dog/erodicemer.txt

**Screenshots**
I'm sorry, I can't screenshot a closed window.

**ViaVersion Dump:**
Cannot generate dump.

Note:
I thought maybe having ViaRewind installed might be a problem, but removing it doesn't fix.

**Comment by FarLanderCraft** [comment]
```
[14:28:23] [Netty Epoll Client IO #0/INFO]: mc.hypixel.net. is force-disabled. (Matches *.hypixel.net)
[14:28:23] [Netty Client IO #2/INFO]: Auto-detected 1.8.x(47) for mc.hypixel.net./172.65.254.166:25565
[14:28:24] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.class_1417: Exception in world tick
	at net.minecraft.class_669.method_2314(class_669.java:1876) ~[intermediary-minecraft-1.8.9-client.jar:?]
	at net.minecraft.class_669.method_2286(class_669.java:889) ~[intermediary-minecraft-1.8.9-client.jar:?]
```

It still throws the exception when just connecting to Hypixel, as I said, I just realized the log didn't reflect that.

**Comment by creeper123123321** [comment]
should be fixed on latest build

**Comment by FarLanderCraft** [comment]
> should be fixed on latest build

I built from source though.

**Comment by FarLanderCraft** [comment]
Never mind i stooped.

**Comment by FarLanderCraft** [comment]
Never mind I double stooped.
https://del.dog/phesawuttu.txt
Latest build still crashing.
@creeper123123321

**Comment by creeper123123321** [comment]
https://github.com/ViaVersion/ViaFabric/commit/dc395910b37112b3d0913adc6de000020f9b583f

**Comment by FarLanderCraft** [comment]
https://del.dog/efigrufihy.txt

**Comment by FarLanderCraft** [comment]
I'm not experienced with this kind of thing, but would it be possible to put all the VR stuff in some sort of experimental setting that can be toggled via a config file? (Since a lot of users wouldn't be using VR anyway.)

(Not trying to be mean or entitled or anything, I only want to be helpful please don't hate me. ;-; )

**Comment by creeper123123321** [comment]
The class name is actually an old suffix name from ViaRift

**Comment by creeper123123321** [comment]
![2021-03-19_20 00 50](https://user-images.githubusercontent.com/7974274/111850016-d3fafc80-88ed-11eb-825c-4a5cc797488c.png)
https://github.com/ViaVersion/ViaFabric/commit/71d3e84cbc2f77a5268e137fdcd7f8a8ed703030 finally fixed
